vgmtrans/vgmtrans

src/main/SeqTrack.cpp
The original comment was very misleading and impeded my efforts in debugging Issue 39.
=> Fix SSEQ 0x94 AddLoopForever comment.

.gitignore, src/main/VGMColl.cpp, src/main/formats/NDSInstrSet.cpp, src/ui/windows/MusicPlayer.cpp, src/ui/windows/WinVGMRoot.cpp
This is a reduced set of changes that I initially made for the SiivaGunner team. Fuller PR and discussion in #82.
=> More Basic Siiva Cleanups

src/ui/qt/main_ui.cpp, src/ui/qt/workarea/VGMFileView.cpp, src/ui/qt/workarea/qhexview/README.md, src/ui/qt/workarea/qhexview/document/qhexcursor.h, src/ui/qt/workarea/qhexview/qhexview.cpp, src/ui/qt/workarea/qhexview/qhexview.h
- Fixed font loading
- Bold and italic variants are now loaded properly
- Fixed alignment issues
- Font now renders at intended size
- Reimplemented zoom, was disabled because of misalignment issues
- Update README
- Added link to original QHexView project
- Visually looks correct on Windows 10 
- Still needs testing on other platforms
=> hexview hotfix

CMakeLists.txt, src/CMakeLists.txt, src/main/CMakeLists.txt, src/ui/qt/CMakeLists.txt
Target macOS Mojave, support compiling under Qt6.
This will look cleaner once we shift from Qt5.9 to Qt5.15 thanks to versionless targets.
This is needed to support compiling under Qt6. macOS 10.13 is still supported by Qt but not brew, making it hard
to automate builds for it; therefore it makes sense to switch to 10.14, which is the oldest supported by brew
=> CMake tweaks

src/main/Options.cpp, src/main/Options.h, src/main/SeqTrack.cpp, src/main/VGMColl.cpp, src/main/VGMMultiSectionSeq.cpp, src/main/VGMSeq.cpp, src/main/formats/AkaoSnesInstr.cpp, src/main/formats/AkaoSnesInstr.h, src/ui/qt/MenuBar.cpp, src/ui/windows/mainfrm.cpp
Fixes a long standing issue with the format of the bank selects we use.
Details are in #264.
This adds support for GS and MMA style bank selection. Perhaps GM and XG could be handy too?
Fixes #264, fixes #11
By playing back various songs and checking the MIDI output.
Appearance of the selector (only tested on macOS)
=> Address bank select issues

.cirrus.yml
Updates the FreeBSD images used by CI
=> CI: Update FreeBSD images

src/main/SeqTrack.cpp
Simplify ReadVarLen
The previous code was really confusing and redundant. I fixed it.
Hopefully it's more clear to you as well.
=> Simplify ReadVarLen

.github/workflows/build.yml
This gets CI going again for Ubuntu, bumps macOS to 12
=> CI: Ubuntu 20.04, macOS 12

src/main/SeqTrack.cpp, src/main/SeqTrack.h, src/main/formats/CPSTrackV1.cpp
Another small improvement to portamento handling in CPS.
=> update cps portamento handling

bin/mame_roms.xml, src/main/formats/CPSInstr.cpp, src/main/formats/CPSSeq.cpp, src/main/formats/CPSTrackV2.cpp
* make CPS3 velocity linearly scaled
* remove CPS3 vibrato/tremelo until further research (clearly not same as CPS2)
* fix CPS3 pitch bend by using a full octave range
* add CPS3 instrument pointers to to the tree view
=> CPS3 fixes

src/ui/qt/workarea/VGMFileTreeView.cpp, src/ui/qt/workarea/VGMFileTreeView.h
Adds a binary search function to insert VGMItem's into the VGMFileTreeView sorted by item offset.
=> Add items into the VGMFileTreeView sorted by offset

src/main/MidiFile.cpp, src/main/MidiFile.h, src/main/SeqTrack.cpp, src/main/SeqTrack.h, src/main/VGMSeq.cpp, src/main/VGMSeq.h
=> Remove everything related to portamento time mode

src/main/DataSeg.h, src/main/VGMItem.cpp, src/main/VGMItem.h, src/ui/qt/workarea/HexView.cpp, src/ui/qt/workarea/HexView.h
Resolves a number of compiler warnings and generally cleans up the code
Trying to drive down all the warnings. Every wee bit helps.
Tested general usage of the app, including HexView.
=> minor code cleanup in VGMItem, HexView and DataSeg

lib/unarr/CMakeLists.txt, lib/unarr/unarr.h, src/main/PSFFile.h, src/main/ScaleConversion.cpp, src/main/formats/CapcomSnesSeq.cpp, src/main/formats/MoriSnesSeq.cpp, src/ui/qt/workarea/VGMFileView.cpp
This should fix the remaining compile warnings (check the commit messages for a better description) :frog: 
I wonder if I should split this PR though :thinking:
=> Various compile warning fixes

.github/workflows/build.yml
This might fix #430 and the linker problems.
=> ci: Use AppleClang + Xcode

src/main/formats/MP2k/MP2kFormat.h, src/main/formats/MP2k/MP2kInstrSet.cpp, src/main/formats/MP2k/MP2kInstrSet.h, src/main/formats/MP2k/MP2kScanner.cpp, src/main/formats/MP2k/MP2kScanner.h, src/main/formats/MP2k/MP2kSeq.cpp, src/main/formats/MP2k/MP2kSeq.h
The only changes made were to remove a couple calls to gsl::narrow_cast<>(), since we removed the gsl-lite lib.
I figure you don't need to review your own code, just putting this up in case you want a last pass. Feel free to force-push over this branch to take credit for your work. As-is, I used "Co-authored" in the commit message.
=> Sykhro's work on the MP2k format

.git-blame-ignore-revs, src/ui/qt/services/MenuManager.cpp, src/ui/qt/services/commands/Command.h, src/ui/qt/services/commands/SaveCommands.h, src/ui/qt/workarea/RawFileListView.cpp, src/ui/qt/workarea/VGMCollListView.cpp, src/ui/qt/workarea/VGMFileListView.cpp
Just like RawFile, this integrates the MenuManager with the VGMCollListView.
Tested the menu options. They're working for single and multi selection.
=> menu: integrate MenuManager with VGMCollListView

src/main/util/common.cpp
This fixes a compile error on my Arch Linux system with GCC 14
=> Add missing algorithm header

.github/workflows/build.yml
Attest binaries built from our CI as a security measure
https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/
N/A
=> CI: Introduce attestation for generated artifacts

.github/workflows/build.yml
Add missing libfuse library
Add missing libfuse library so AppImage will compile in ci.
Allows AppImage to build without erroring out.
Ran with workflow_dispatch on patch-4 branch.
=> Add fuse library

src/main/formats/common/PSXSPU.cpp
Refactoring of PSXSampColl:searchForPSXADPCM()
The same heuristics are still in place, but I've refactored the code, loosened tolerances, added validation for the filter / shift byte (the first byte of each frame), and crucially added back-scanning after the first phase of detection. 
The forward pass heuristics can skip past smaller samples, back-scanning corrects this. We iterate backward 16 bytes at a time (since we've found the frame boundary) and run looser heuristics until we determine we're no longer in sample data (or when we hit the 0x5000 byte back scan limit).
This seems to be working very well.
Our detection of playstation ADPCM sample collection blocks was still unreliable. While the last set of changes reduced the number of false positives, we still often detected the wrong …
=> Refactor and improve PSXSampColl:searchForPSXADPCM()

README.md
Add a screenshot to the README.md. Hex data is randomized (via a modification to hex printing function in HexView.cpp) to avoid copyright concerns.
=> Add screenshot to README.md

src/main/formats/NDS/NDSInstrSet.cpp
=> add more granular UI items for NDS instrument sets

src/ui/qt/MenuBar.cpp, src/ui/qt/MenuBar.h
- move dock window show/hide options to a new "Windows" menu
- rename the "Options" menu to "Conversion"
=> Menu cleanup

src/main/components/instr/VGMRgn.h, src/main/conversion/SF2Conversion.cpp, src/main/conversion/SF2File.cpp, src/main/conversion/SF2File.h, src/main/conversion/SynthFile.h, src/main/formats/SegSat/SegSatInstrSet.cpp, src/main/formats/SegSat/SegSatInstrSet.h, src/main/formats/SegSat/SegSatScanner.cpp, src/main/formats/SegSat/SegSatScanner.h
This adds support for SoundFont 2's pitch LFO-related generators and utilizes them for Sega Saturn's software and hardware pitch LFOs. VGMRgn and SynthFile are given three new methods:
```
void setLfoVibFreqHz(double freq);
void setLfoVibDepthCents(double cents);
void setLfoVibDelaySeconds(double seconds);
```
When a region has depth and frequency > 0, the relevant SF2 generators are added. Likewise, when delay is > 0, the corresponding generator is added. 
The Saturn driver provides pitch LFO in two ways: hardware and software. The hardware LFO is simple, and supports frequency and depth. The software LFO adds support for delay and depth fade-in - delay being relative to note-on, and fade-in beginning after the delay period. 4 byte "PLFO" tables in instrument sets define the parameters …
=> Add Sega Saturn software and hardware pitch LFO support
