src/main/SF2File.cpp, src/main/formats/AkaoSnesInstr.cpp, src/main/formats/AkaoSnesInstr.h, src/main/formats/AkaoSnesScanner.cpp, src/main/formats/AkaoSnesScanner.h, src/main/formats/AkaoSnesSeq.cpp, src/main/formats/AkaoSnesSeq.h
The commit comment on bf25c3c has more details, but this adds percussion support to the AkaoSnes format (which was previously listed in the source as "TODO: percussion note"). As far as I've found, the percussion table is used in Chrono Trigger, Front Mission, and Front Mission - Gun Hazard.
Some percussion is implemented using the SPC700 white noise capability, and this commit doesn't fix that, but it does fix major parts of a lot of the songs from those games.
=> Added drumkit/percussion support to the AkaoSnes format.

src/main/formats/MP2kScanner.cpp, src/main/formats/MP2kScanner.h
Change use of uint32_t to u32 and include common.h.
In trying to build, I encountered an error with the type uint32_t not being declared in MP2kScanner.h and in investigating i discovered that in many places in MP2kScanner.cpp, u32 declared in common.h is used, so to make the code compile and make it consistent with the rest of the module, I changed it to use the equivalent u32 type.
Fixes a compile failure with the particular module.
Program compiles and runs, however I don't know what games use this particular format nor do I likely have them on hand so someone more familiar with this format would have to test functionality.
=> [core] Fix MP2kScanner.(h|cpp) compile.

src/main/formats/Vab.cpp
Edit: I changed this from a nit, to an actual bug fix.
=> Fix: VAB parsing 1 too many instruments

src/main/VGMSeq.cpp, src/main/VGMSeq.h, src/main/formats/NinSnesSeq.cpp
Had to create a new track variable that will skip incrementing the timer when set to true. The timer is incremented when all tracks are done processing, which EVENT_END forces to happen. However, the timer is then incremented, and thus incurs a one tick delay. This normally does not happen (Yoshikazu Yao's later builds, not yet supported, is a possible exception because there is some sort of two-pass system in there, but it could also be caused by lag, which vgmtrans does not need to emulate), as I recall that the next section is then immediately processed in at least some of the cases.
This merge request closes #155.
My test environment is:
* Operating System+version: macOS Catalina 10.15.7
* VGMTrans version: 1.1
This is my test case that I used (mostly because I had used a low enough …
=> [NinSnes] Don't increment the timer after EVENT_END ($00 VCMD)

src/main/DLSFile.cpp, src/main/DLSFile.h
This fixes a compile error (at least on my Linux system with GCC)
I initially added this in the AUR package but with a note to upstream this :frog:
=> DLSFile: Add missing header

src/main/SeqTrack.cpp
#360 had a mistake with operator precedence between & and ==. `if(c & 0x80 == 0)` is always false because it's basically equivalent to `if(c & (0x80 == 0))`.
=> Fix SeqTrack::ReadVarLen

bin/mame_roms.xml, src/main/formats/CPSInstr.cpp, src/main/formats/CPSScanner.cpp, src/main/formats/CPSScanner.h, src/main/formats/CPSSeq.cpp, src/main/loaders/MAMELoader.cpp
Fixes for CPS games
* Add missing CPS3/ZN-1/ZN-2 games to mame_roms.xml, update CPS3 game rom paths to use latest MAME expectations
* Don't attempt to decrypt SFIII 2nd Impact
* alphabetize rom set order in mame_roms.xml
* fixed apparently faulty default pitch bend range for CPS format ver 2 and above
Not much logic changed here. Will merge on my own when tests pass.
=> Update CPS game support

src/main/MidiFile.cpp, src/main/MidiFile.h, src/main/SeqTrack.cpp, src/main/SeqTrack.h, src/main/VGMSeq.cpp, src/main/VGMSeq.h, src/main/formats/CPSSeq.cpp, src/main/formats/CPSTrackV1.cpp
* Add SysexEvent class to simplify defining sysex midi events
* Update Reset events to use SysexEvent
* Add PortamentoTimeMode event for usage in upcoming VST playback
* Add portamentoTimeMode property to VGMSeq
* Improve portamento implementation again in CPS format
* delete midi in VGMSeq destructor
* rename MastVolEvent -> MasterVolEvent
=> Add SysexEvent class and update CPS portamento handling

src/ui/qt/main_ui.cpp
When running Windows 10 on a 4k monitor with 150% display size (the default), the app looks huge. Removing `setAttribute(Qt::AA_EnableHighDpiScaling);` fixes the issue.
I'm curious if there is another configuration that prompted the use of these settings. For me, running on a high dpi monitor, it seems to be conflicting with the default method Windows' uses to scale up.
=> remove high dpi scaling and pixmaps for Qt version < 6

src/main/Root.cpp, src/main/Root.h, src/main/common.h, src/main/loaders/MAMELoader.cpp, src/ui/qt/CMakeLists.txt, src/ui/qt/QtVGMRoot.cpp, src/ui/qt/QtVGMRoot.h
Also updates the CMakeLists to copy entire /bin directory to bundle's /Contents/Resources directory on MacOS.
Currently MacOS fails to load the mame_roms.xml file because the default working directory when opening a Mac application is the system root. This adds a system-specific function to get the path to the application's resource directory, which for all other platforms is the same path as the executable, at least for now.
This fixes the MAME loader on MacOS
Tested on MacOS Sonoma, Windows 10, and Ubuntu 22.
=> Add UI_GetResourceDirPath() and update MAMELoader to use it

src/main/formats/CPSTrackV1.cpp, src/main/formats/CPSTrackV1.h
Use decacents per sec instead of cents per sec for portamento timing, aligning with a [change to the fluidsynth fork](https://github.com/mikelow/fluidsynth/commit/b02801e03b410fc24e10af42f1fd160f9c46da93) used by the [vst plugin](https://github.com/mikelow/juicysfplugin)
The reason for this change is to allow faster portamento slides than cents per second allows. CPS sequences often use a portamento time of 0, which emulates a legato effect (no slide, but no attack phase) - effectively the same as instantaneous portamento. A [trill between 5ths](https://www.youtube.com/watch?v=tc7nRcTfB5g) at maximum cents per second value (16,383) still causes audible slide.
I investigated using legato pedal events when CPS sets portamento time to 0, but the default MIDI behavior, at least as implemented …
=> Add initial portamento value to CPS, update to use decacents per second

src/main/SeqTrack.cpp, src/main/formats/CPSTrackV1.cpp
In CPS format, when a tied note ends via the occurrence of a new non-tied note, write the new note's ON event before the previous note's OFF event to allow portamento effect.
I think it's finally all solved, knock on wood.
=> CPS Portamento fix... again

src/main/MidiFile.cpp, src/main/MidiFile.h, src/main/SeqTrack.cpp, src/main/SeqTrack.h, src/main/formats/CPSSeq.cpp, src/main/formats/CPSTrackV1.cpp, src/main/formats/CPSTrackV1.h
Turns out this was not as hard to implement I thought it would be.
This changes the CPS driver to express portamento time as a duration in milliseconds in order to increase compatibility with midi players/instruments. MIDI does not define a standard for interpreting portamento time, but millisecond duration is how Fluidsynth does it. BASS does something similar, but there are audible differences, both in terms of timing and more generally when it decides to apply portamento. (It appears [BASS doesn't support](https://www.un4seen.com/doc/#bassmidi/BASS_MIDI_StreamEvent.html) controller 37 - portamento time fine - though I don't think this entirely accounts for the timing difference).
When comparing this version using Fluidsynth against the prior portamento time-as-rate implementation, I …
=> Use duration portamento time on CPS

src/ui/qt/workarea/HexView.cpp, src/ui/qt/workarea/HexView.h, src/ui/qt/workarea/VGMFileView.cpp, src/ui/qt/workarea/VGMFileView.h
Resizing the app window causes both hex view and tree view to resize 1:1. I've added logic to limit the maximum width of the hex view so that it doesn't expand beyond the ASCII text column, allowing extra space to be devoted to the tree view. 
I also added logic so that increasing/decreasing the font size will make the hex view proportionally grow/shrink, so if you've repositioned the splitter to, say, hide the ASCII view, you won't need to reposition it after a font size change.
Also, I found that increasing/decreasing the font size in increments of 0.5 was sometimes having no effect, as Qt seems inexact about font sizing. I added some logic to increment the font size until there is an actual change in character width.
I also decreased the default font size a bit.
Tested on Mac and …
=> Improvement to HexView splitter behavior and font increase/decrease

src/ui/qt/workarea/VGMFileListView.cpp, src/ui/qt/workarea/VGMFileListView.h
This improves the appearance and resizing behavior of the VGMFileListView. There are a few issues I want to fix:
1. The headers are spaced evenly and cannot be resized
2. Resizing should expand/contract the Name header instead of both headers evenly
3. There is a little splitter at the right edge of the Format section header
This fixes the above problems. I've also added logic so that the splitter resizes both sections so that their widths sum to the full header width.
The initial width of the Format section header is set by calculating the width of the "Format" text itself and adding some padding. This is necessary as the font will be different per platform.
I disable the horizontal scroll bar and override the scrollContentsBy() event so that horizontal scrolling is impossible. this is …
=> Improve VGMFileListView Headers

src/main/Format.cpp, src/main/Format.h, src/main/Root.cpp, src/main/Root.h
When quitting the app, if a file was ever loaded into the app, MacOS would report a crash after quitting. Looking into the crash logs, it became clear this is caused by the destruction order of static objects. Specifically, the VGMRoot object, the FormatMap registry object, and all of the Format objects are declared statically. The destructor of VGMRoot references these other static instances at some point down the stack trace, but they might be destroyed before VGMRoot is.
To fix the issue, I made the FormatMap registry and Format instances into static pointers, ensuring that they'll be destroyed after VGMRoot (upon app exit, or when we delete them ourselves).
It's unclear to me if best practice is to actually delete all of these instances on close of the app, as we're mostly doing, …
=> Fix crashes on quit related to static destruction order

src/ui/qt/util/MarqueeLabel.cpp
Images attached:
Before:
After:
Update:
Tested on Windows and working fine. The app doesn't respect Windows dark mode in general, though.
=> Use system WindowText color for MarqueeLabel (respects light/dark mode)

.github/workflows/build.yml, .gitmodules, lib/filesystem/CMakeLists.txt, src/ui/qt/CMakeLists.txt, src/ui/qt/main_ui.cpp, src/ui/qt/qt.conf
Closes #370 
- drops support for Qt5
- upgrades CI and vendored Windows submodule to Qt6
- uses clang 17 on macOS & Linux
- bumps macos runner to 13.0
Qt6 brings improvements around performance, accessibility, features. It has better behaviour with Wayland on Linux and fully supports dark mode on Windows. 
CI now uses Clang 17 on both Linux and macOS. This results on better performance on both platforms.
Confirmed working:
- macOS 12, M1, built locally
- macOS 12, M1 using Rosetta, built CI
- Windows 11, x64, built locally
- Windows 11, x64, built on CI
Linux builds might have issues due to Wayland but I will work on #356 soon, so we can leave it for now.
=> Upgrade to Qt6, drop Qt5 support

README.md, bin/mame_roms.xml
This does some cleanup to mame_roms.xml and adds the no-cd CPS3 definitions in supplement to the merged rom definitions. I could be clever and add logic so that merged sets can reference the no-cd sets and reduce some repetition, but it's not worth it as this will likely only ever apply to the 5 cps3 games. Plus, I'd sooner work on migrating to json from xml.
I've also updated the readme to reflect support for CPS3, and I've removed reference to the old WTL build in the "How to compile it" section.
=> mame_roms.xml and readme update

src/ui/qt/QtVGMRoot.cpp, src/ui/qt/QtVGMRoot.h, src/ui/qt/workarea/VGMCollListView.cpp
This is the counterpart to #405 for batch deletion of collections (when deleting a raw file, for example). Vastly improves performance for the same reasons discussed before.
=> Use beginResetModel/endResetModel for batch deletion of collections

bin/mame_roms.xml, src/main/formats/CPSInstr.cpp
Minor bug: seems a release rate of 0 means infinite release, not no release.
Also fix up ssf2 mame_roms.xml definition.
Will merge this on my own since it is too minor to warrant review.
=> Fix CPS release rate of 0 bug

src/ui/qt/workarea/VGMFileListView.cpp
Enable multiple selection in VGMFileListView, fix logic for deleting all selected files. 
The old for loop was broken because the file pointed to by `index` changed with every onClose() call.  What I wouldn't do for a simple map() function instead of reserving space for a vector and looping to populate it. I know about std::transform, but that is just unreadable.
Might as well allow multi selection.
Tested on MacOS, selections of various size.
=> VGMFileListView multi select and deletion

src/ui/qt/workarea/RawFileListView.cpp
For some reason (probably related to fiddling with the installed build tools) I started seeing exceptions thrown on the Windows build in RawFileListViewModel::RemoveRawFile() upon loading a file that gets unpacked. It looks like we are trying to remove rows at an index that doesn't necessarily exist. The code in this function is odd in that there's no guarantee a removed RawFile will be at the last index, and besides this, it appears that we're supposed to:
1. Call beginRemoveRows()
2. Remove the rows from the data source
3. Call endRemoveRows()
At any rate, we have the same non-adherence in AddRawFile() and it's not causing a fuss, possibly because in that case, the last index is actually what is updated every time.
Anyway, for now, I've just added a dataChanged() in place of …
=> use dataChanged() on raw file removal, for now

src/main/Root.cpp, src/main/loaders/SPC2Loader.cpp, src/main/loaders/SPC2Loader.h
This adds a loader for the SPC2 format (.sp2), another archive format for spc files. This format's distinction is its ability to decompress individual files without having to decompress the entire archive at once, not that this matters for our purposes.
Ran it on MacOS.
=> Add SPC2Loader

src/main/VGMFile.cpp, src/main/VGMFile.h, src/main/VGMInstrSet.cpp, src/main/VGMInstrSet.h, src/main/VGMSampColl.cpp, src/main/VGMSampColl.h, src/main/VGMSeq.cpp, src/main/VGMSeq.h, src/ui/qt/CMakeLists.txt, src/ui/qt/QtVGMRoot.cpp, src/ui/qt/services/MenuManager.cpp, src/ui/qt/services/MenuManager.h, src/ui/qt/services/commands/GeneralCommands.h, src/ui/qt/services/commands/SaveCommands.h, src/ui/qt/util/UIHelpers.cpp, src/ui/qt/util/UIHelpers.h, src/ui/qt/workarea/VGMFileListView.cpp, src/ui/qt/workarea/VGMFileListView.h
As [promised](https://github.com/vgmtrans/vgmtrans/pull/417#issuecomment-1858931378), this PR adds batch conversion so that when multiple VGMFiles are selected, they can all be saved in a single command. But wait, there's more! I didn't just tack this on to VGMFileListView. I wrote a generalized solution that will hopefully make it easy to create menus for any type across the entire app.
This PR introduces a new "service" for menu generation called `MenuManager`. The idea is that you can register a set of "Commands" to any type you so desire, where a `Command` represents a menu action, and then pass an instance of any type to `MenuManager::GetCommands()` to retrieve the eligible `Command`s of the object. The Command object, in turn, can execute the action.
Commands require data, of …
=> Add MenuManager and integrate it into VGMFileListView

bin/mame_roms.xml, src/main/ScaleConversion.cpp, src/main/ScaleConversion.h, src/main/formats/CPSFormat.h, src/main/formats/CPSInstr.cpp, src/main/formats/CPSInstr.h, src/main/formats/CPSScanner.cpp, src/main/formats/CPSSeq.cpp, src/main/formats/CPSTrackV1.cpp, src/main/formats/CPSTrackV1.h, src/main/formats/OkiAdpcm.cpp, src/main/formats/OkiAdpcm.h, src/main/formats/PSXSPU.h
This adds the CPS1SampleInstrSet and CPS1SampColl classes, which support the OKI MSM6295 sound chip used by CPS1.
The OKI MSM6295 provides 4 channels of 4-bit ADPCM audio. I've added the MAME code for decoding the specific ADPCM format. This chip can change the channel volume but not the pitch. As such, it is used primarily for percussion instruments and sound effects.
This is a precursor to adding support for the FM synthesis chip via a new JUCE-based virtual instrument plugin. I'm working on that project (which I've dubbed "ymmy") in parallel.
CPS1/2/3 sets still load and playback without issue.
=> Add CPS1 sampled playback

bin/mame_roms.xml, src/main/formats/CPS1Instr.cpp, src/main/formats/CPS1Instr.h, src/main/formats/CPS1Scanner.cpp, src/main/formats/CPS1Scanner.h, src/main/formats/CPS2Format.h, src/main/formats/CPS2Instr.cpp, src/main/formats/CPS2Instr.h, src/main/formats/CPS2Scanner.cpp, src/main/formats/CPS2Scanner.h, src/main/formats/CPSSeq.cpp, src/main/formats/CPSSeq.h, src/main/formats/CPSTrackV1.h, src/main/formats/OkiAdpcm.cpp, src/main/formats/OkiAdpcm.h
Note that this PR is basing on top of the previous "okiadpcm" branch PR.
Adding sampled playback for CPS1 expanded the already bloated CPSScanner.cpp and CPSInstr.cpp files. Since the logic for CPS1 is unique, I've moved it into respective CPS1Scanner.cpp and CPS1Instr.cpp files and added a "CPS1" Format.
This leaves us in an awkward spot, as we would have both a "CPS1" format and a "CPS" format, not to mention a CPS1Scanner and a CPSScanner. Thus I've renamed the CPS format to CPS2, CPSScanner to CPS2Scanner and CPSinstr to CPS2Instr. Unfortunately, "CPS2" is partly a misnomer here as both files and formats cover CPS2/CPS3 and some ZN-1/ZN-2 games. Further muddying the waters, CPSSeq, at least for now, is still used by all formats above, and the CPSTrackV1/V2 classes do not align cleanly …
=> Move CPS1 logic into separate files. Look away from the mess

.github/workflows/build.yml, LICENSE/LICENSE, LICENSE/LICENSE_oki_adpcm_state, src/ui/qt/About.cpp, src/ui/qt/About.h, src/ui/qt/resources/resources.qrc
This adds a bit of structure for adding third party licenses to our repo and the app.
- I added a LICENSE directory that stores our license and the licenses of external source code.
- I added a preface to our LICENSE which acknowledge the use of external source code and directs readers to the LICENSES directory and About dialog.
- I added a new License tab to the About dialog that provides a simple interface for browsing licenses.
To add a new third-party license, simply put the license in the LICENSES directory and add an entry for the file in resources.qrc with an alias of "legal/\<name that should appear in About Dialog\>".
Tested on MacOS. Will test on Windows/Linux.
=> License disclosure stuff

src/main/VGMColl.cpp, src/main/VGMColl.h, src/ui/qt/workarea/MdiArea.cpp, src/ui/qt/workarea/MdiArea.h, src/ui/qt/workarea/VGMCollView.cpp, src/ui/qt/workarea/VGMCollView.h, src/ui/qt/workarea/VGMFileListView.cpp, src/ui/qt/workarea/VGMFileListView.h
**Update: I discovered that this PR is vulnerable to a separate dangling pointer bug that can cause a crash. It's fixed here: #447**
I would have split this into two PRs, but there's overlap.
1) There's a bug whereby closing an MDI window causes every other open MDI window to become windowed instead of maximized. To fix this, I've added a new ensureMaximizedSubWindow() function that gets called every time the subWindowActivated signal is fired by MdiArea.
2) The WTL version had a UI behavior whereby selecting a file in the vgm file list or focusing its MDI window caused both to be selected/focused. I've added this behavior back in and extended it to the VGMCollView. 
Thorough clicking and clacking.
The MDI window bug. Closing a window often results in something like this:
=> Fix mdi window bug, add unified vgm file selection behavior

src/ui/qt/workarea/VGMCollListView.cpp
Currently, double clicking a collection puts the collection name into an edit mode. I don't think this provides much value to the user.
I can think of two more-helpful responses to a double click:
1) play/pause the sequence player for the clicked collection
2) open up the hex view for the associated sequence file of the clicked collection
I went with 1.
I also changed the selection behavior to only allow selection of one collection at a time, since that is the paradigm we use with the VGMCollView (to the left of the VGMCollListView).
Played around with it. Haven't been able to break it.
=> Change collection list double-click behavior to play/pause

src/main/Root.h, src/ui/qt/QtVGMRoot.cpp, src/ui/qt/QtVGMRoot.h, src/ui/qt/workarea/VGMCollListView.cpp, src/ui/qt/workarea/VGMCollView.cpp, src/ui/qt/workarea/VGMCollView.h
Turns out there is a crashing bug in #446. The issue is a dangling pointer in VGMCollViewModel that #446 accesses. When a user deletes a collection, VGMCollViewModel does not check if the deleted collection is the one pointed to by its m_coll property.
In #446, if the user selects a collection, then deletes it by removing any of its files, then attempts to open the MDI window of any file, the VGMCollViewModel::containsVGMFile() may cause a crash when it dereferences m_coll.
This fixes the bug by handling the UI_RemoveVGMColl() callback in VGMCollView to check if the removed collection is selected. If so, it updates the model accordingly. Yes, we should probably be using smart pointers here and everywhere.
Note that I removed `UI_RemovedVGMColl()` and upgraded `UI_RemoveVGMColl(VGMColl*)` …
=> Fix VGMCollView not updating its model immediately after VGMColl deletion

src/ui/qt/workarea/MdiArea.cpp, src/ui/qt/workarea/VGMFileView.cpp
There is a Windows-specific bug that occurs when a VGMFile is opened into the MdiArea. A new window will flash and then disappear before the sub window is created.
The culprit is an unnecessary call to `m_hexScrollArea->show()` in `VGMFileView.cpp`.
I've removed this call, and I've also changed the call in MdiArea from `tab->show()` to `tab->showMaximized()`. While this change isn't necessary for the window to display maximized, it seems more reflective of our intentions. I'm confused why windows are appearing maximized even when we call `tab->show()`. Unfortunately, this change doesn't obviate the need for my last fix with `ensureMaximizedSubWindow()`.
Tested on Windows 10
=> Fix a Windows bug causing new subwindows to flash

.github/workflows/build.yml
Add MacOS arm64 as a CI target.
Note that Github seems to be severely throttling their arm64 machines. I advise we allow ourselves to merge future pull requests regardless of whether the arm64 build is pending.
=> ci: add macos arm64 target

src/ui/qt/CMakeLists.txt, src/ui/qt/widgets/SnappingSplitter.cpp, src/ui/qt/widgets/SnappingSplitter.h, src/ui/qt/workarea/HexView.cpp, src/ui/qt/workarea/HexView.h, src/ui/qt/workarea/VGMFileView.cpp, src/ui/qt/workarea/VGMFileView.h
This adds a new QSplitter subclass to which you can apply "SnapRanges" - upper and lower bounds which the splitter will snap to, preventing sizing to any value in between. It's basically the same behavior as when a QSplitter nears collapse of one of its views.
The use case is to improve how the HexView responds to window resizing and manual splitter resizing.
Relatedly, I've added logic for HexView to hide the address prefix when it cannot fit on the screen.
Making the HexView sizing less awkward.
Tested on Windows and MacOS.
https://github.com/vgmtrans/vgmtrans/assets/1659535/829430c9-4e37-47a9-be64-949849675f3c
=> Add SnappingSplitter for HexView

src/ui/qt/workarea/VGMFileTreeView.cpp, src/ui/qt/workarea/VGMFileTreeView.h, src/ui/qt/workarea/VGMFileView.cpp
Refines some of the key and mouse event handling in the VGMFileTreeView.
This adds handlers for keyPressEvent, mousePressEvent, and mouseDoubleClickEvent.
On the keypress side, I've added logic so that a left arrow key will change the selected item to the parent, so long as the current item is not expanded. This is a common convention across operating systems.
On the mouse event side, I've made it so that clicking an already selected item will deselect it. This is to provide parity with the HexView behavior, where clicking an item will both select and deselect it. Because clicking quickly registers as a double click and overrides the regular click handler, I added the same logic to the double click handler.
Also, I moved but did not edit the addVGMItem() method to be consistent with its …
=> VGMFileTreeView behavior tweaks

src/ui/qt/workarea/VGMCollListView.cpp
Just a couple small changes:
- First, it turns out the unwanted name editing behavior in the collection list view is due to setting the `ItemIsEditable` flag, so I removed it.
- Second, on MacOS, the collection list is reserving space for the horizontal scrollbar when it shouldn't. I fixed this. This is probably a Qt bug affecting wrapping QListViews that scroll horizontally, since Qt otherwise behaves in the standard fashion of not reserving space for MacOS's disappearing scrollbars. 
Run on MacOS Sonoma.
Minimum height required to show 6 rows:
Before
After
=> Collection list polish

src/ui/qt/workarea/VGMCollListView.cpp, src/ui/qt/workarea/VGMCollView.cpp, src/ui/qt/workarea/VGMCollView.h, src/ui/qt/workarea/VGMFileListView.cpp
This adds keypress handling for the enter and return keys (which it treats the same). In the file list view and the collection view, these keys open the current file just a double click would. In the collection list view, it toggles playback just like the space bar does.
Getting the app to conform to standard UI input behavior.
Tested on Mac.
=> Add enter and return key behavior for list views

src/ui/qt/MainWindow.cpp, src/ui/qt/util/Metrics.h, src/ui/qt/widgets/TitleBar.cpp, src/ui/qt/widgets/TitleBar.h, src/ui/qt/workarea/MdiArea.cpp
Also:
- set TitleBar height sizeHint to be the same as MDI tabs for visual cleanliness
- rename "Raw Files" title bar to "Scanned Files" for clarity to users
Tested on Mac, Windows, Ubuntu.
=> Add Metrics.h for common UI constants

src/ui/qt/widgets/SnappingSplitter.cpp, src/ui/qt/widgets/SnappingSplitter.h, src/ui/qt/workarea/HexView.cpp, src/ui/qt/workarea/HexView.h
Also, update HexView to only draw ASCII when it's visible.
Depending on the size of the window, the SnappingSplitter may snap to an upper bound but actually fall short of its size target. This is due to minimum size constraints - the view on the opposite side of the splitter can only shrink to its minimum size, which may not be enough to accommodate.
The new logic checks the actual size after the snap and reverts if the target size wasn't realized.
Run on MacOS
=> Prevent SnappingSplitter from snapping to non-target size

src/ui/qt/CMakeLists.txt, src/ui/qt/main_ui.cpp, src/ui/qt/services/NotificationCenter.h, src/ui/qt/services/Settings.cpp, src/ui/qt/services/Settings.h, src/ui/qt/util/Metrics.h, src/ui/qt/widgets/TableView.cpp, src/ui/qt/workarea/VGMFileListView.cpp, src/ui/qt/workarea/VGMFileTreeView.cpp, src/ui/qt/workarea/VGMFileTreeView.h
Two additions here:
First, is the introduction of a `Settings` class, a singleton that accesses QSettings ~~and emits signals when settings have been changed~~ (⚠️ Update: I'm now routing through NotificationCenter as I believe it's more intuitive). I'm attempting to use nested structures to group the settings and make code more readable. For example, the first component of the app to use Settings is the VGMFileTreeView, so I've added a nested struct called VGMFileTreeViewSettings with an instance that is simply the class name: VGMFileTreeView. Thus, the following lines access the showDetails setting:
`Settings::the()->VGMFileTreeView.showDetails()`
`Settings::the()->VGMFileTreeView.setShowDetails()`
~~QObject signals have some limitations. They cannot be static, and they cannot be used …
=> Add Settings service, add "Show Details" button to VGMFileTreeView

src/ui/qt/workarea/VGMFileTreeView.cpp, src/ui/qt/workarea/VGMFileTreeView.h
The app is running fine on MacOS without these quirk fixes. Fixed by Qt6? Other code changes? No idea.
=> Remove a couple MacOS specific fixes for VGMFileTreeView 

src/main/Root.cpp, src/main/Root.h, src/ui/cli/CLIVGMRoot.cpp, src/ui/cli/CLIVGMRoot.h, src/ui/qt/QtVGMRoot.cpp, src/ui/qt/QtVGMRoot.h
- remove Root::UIExit() and Root::UI_PreExit()
- re-add UI_CloseRawFile() and call it in Root::CloseRawFile()
- remove unused CLIVGMRoot::UI_GetOpenFilePath() and CLIVGMRoot::UI_Exit()
- make Root::Init() virtual, since it's overridden by the CLIVGMRoot class
=> Small fixes / cleanup for Root and CLIVGMRoot

src/main/Root.cpp, src/main/Root.h, src/main/io/RawFile.cpp, src/ui/qt/workarea/RawFileListView.cpp, src/ui/qt/workarea/VGMFileListView.cpp
Replaced some iterator based loops with range-based loops. Also a small hack fix for RawFileListView not redrawing upon deleting the last RawFile.
Note that I fixed a bug in the last PR where I didn't pass a flag to RemoveVGMFile() from CloseRawFile(), which could result in an unwanted recursive CloseRawFile() call. The weird workaround I had is no longer necessary, hence the simplification in Root.cpp.
=> Root file iteration cleanup

src/main/formats/AkaoSnes/AkaoSnesSeq.cpp, src/main/formats/CPS/CPS1Scanner.cpp, src/main/formats/CPS/CPS2Scanner.cpp, src/main/formats/CPS/CPSSeq.cpp, src/main/formats/CPS/CPSTrackV1.cpp, src/main/formats/CapcomSnes/CapcomSnesSeq.cpp, src/main/formats/CompileSnes/CompileSnesSeq.cpp, src/main/formats/FFT/FFTSeq.cpp, src/main/formats/KonamiSnes/KonamiSnesSeq.cpp, src/main/formats/MP2k/MP2kInstrSet.cpp, src/main/formats/MoriSnes/MoriSnesSeq.cpp, src/main/formats/MoriSnes/MoriSnesSeq.h, src/main/formats/NamcoSnes/NamcoSnesSeq.cpp, src/main/formats/NinSnes/NinSnesSeq.cpp, src/main/formats/RareSnes/RareSnesSeq.cpp
@TheComputerGuy96, and FYI @sykhro 
This pulls in the commits from from #475 but excludes the vendored zlib update and enabling of -Werror. Instead, we will switch to importing zlib-ng as a git submodule in a future PR, at which point we can probably also enable -Werror. Note that I also added a commit that addresses some of the issues in MoriSnesSeq.cpp.
Given that I already reviewed #475, I will leave this up for a couple days for comment and then merge it if there is no objection or discussion.
In order to keep our git history clean, I've moved the #475 commits into a new branch to avoid the unnecessary vendored update to zlib.
Tested that MoriSnes and FFT drivers are still working as expected.
=> Clang warnings fixup

bin/mame_roms.xml, src/main/formats/CPS/CPS2Instr.cpp, src/main/formats/CPS/CPS2Instr.h, src/main/formats/CPS/CPSTrackV2.cpp, src/main/loaders/MAMELoader.cpp, src/main/loaders/MAMELoader.h
This fixes a number of problems with the CPS3 driver and also fixes a volume/expression miscalculation issue affecting both CPS3 and CPS v2 (mostly ZN-1 / ZN-2 titles).
* for cps3/v2 don't use CPS2 v1 table for volume/expression, instead treat values as linear scale percent for now (we can add a table later)
* fix instrument length determination, don't rely on 0xFFFF separator - fixes incorrect samples
* add high byte for region sample index - fixes incorrect samples
* add a "deinterlace_pairs" load method to MAMELoader which deinterlaces two files at a time from a rom group entry. Needed to load the rest of sfiii3's samples
=> CPS3 / CPS v2 fixes

bin/mame_roms.xml, src/main/formats/CPS/CPS2Instr.cpp, src/main/formats/CPS/CPS2Instr.h, src/main/loaders/MAMELoader.cpp, src/main/loaders/MAMELoader.h
This fixes a bug affecting CPS3 audio quality. Interlaced CPS3 sample roms were loaded in the wrong order, creating scratchy audio. It also implements the region fine_tune value in CPS versions >= 1.3 and < 2.0 (most titles do not utilize this, but strider2 is an exception).
- add LoadOrder enum to MAMELoader, and logic for each LoadMethod to load roms in reverse order
- fix CPS romgroup entries that need to load in reverse order
- CPS: Add instrument region fine_tune byte for CPS versions >= 1.3 and < 2.0
I examined the samples under a magnifying glass (Audacity).
=> More CPS3 fixes

.github/workflows/build.yml, .gitignore, CMakeLists.txt, CMakePresets.json, src/main/CMakeLists.txt, src/ui/cli/CMakeLists.txt, src/ui/qt/CMakeLists.txt
- Switch to using CMakePresets to manage CMake settings instead of baking them inside the root CMakeLists
- Add Windows ARM64 job
All CMake projects should be pluggable and should not define properties of the compiler. Flags and other settings are to be put in external setting files (toolchain files) to prevent potential clashes.
`cmake-presets` is a "new" way of managing CMake settings, acting more or less like VS solution configurations.  It was introduced with CMake 3.19 but we require functionality that was added with CMake 3.21.
With this change, CMakeLists is cleaned up and compiling is simpler. For example, on Windows:
```
cmake --preset win-x64
cmake --build --preset win-x64-release
```
will set up & compile for Windows x64 in Release mode.
Many IDEs speak cmake-presets too (VS, …
=> Use CMakePresets, misc CI improvements

src/main/Root.cpp, src/main/Root.h, src/ui/cli/CLIVGMRoot.cpp, src/ui/cli/CLIVGMRoot.h, src/ui/qt/ManualCollectionDialog.cpp, src/ui/qt/workarea/RawFileListView.cpp, src/ui/qt/workarea/VGMCollListView.cpp, src/ui/qt/workarea/VGMCollView.cpp, src/ui/qt/workarea/VGMFileListView.cpp
This is #487 without the .clang-format changes:
- Renamed VGMRoot's vRawFile, vVGMFile, vVGMColl to m_rawfiles, m_vgmfiles, m_vgmcolls
- Made the above fields private and created getter functions: rawFiles(), vgmFiles(), vgmColls()
- Renamed pRoot to s_root
I'd still like to change up our .clang-format file, especially so that it doesn't keep using right aligned pointers and references (int *myPtr).
=> Root field getters

src/main/components/VGMColl.cpp, src/main/formats/CPS/CPS2Instr.cpp, src/main/formats/CPS/CPS2Instr.h, src/main/formats/CPS/CPSSeq.cpp
We were using the CPS2 driver iteration rate for CPS3. This uses the CPS3 rate, which is the vblank irq. I also fixed a bug I recently introduced whereby a check to ensure sample indexes are valid during synth file generation occurred after already setting the possibly bad index on the region.
Nothing appears to have broken in CPS2 and CPS3 playback.
=> CPS3: use CPS3-specific IRQ rate for timing calculations, fix out-of-bounds sample check

src/main/conversion/MidiFile.cpp, src/main/formats/CPS/CPSTrackV1.cpp, src/main/formats/CPS/CPSTrackV2.cpp, src/main/formats/CPS/CPSTrackV2.h
Also add the CPS3 'meta event' event, and fix an incorrect call in MidiTrack::InsertCoarseTuning (method is unused).
UPDATE: I also added proper handling of LoopForever so that tracks don't abruptly cut off before the rest of a sequence.
=> CPS3: Add track fine-tune event

.git-blame-ignore-revs, src/ui/qt/CMakeLists.txt, src/ui/qt/services/MenuManager.cpp, src/ui/qt/services/MenuManager.h, src/ui/qt/services/commands/Command.h, src/ui/qt/services/commands/GeneralCommands.h, src/ui/qt/services/commands/SaveCommands.h, src/ui/qt/workarea/RawFileListView.cpp, src/ui/qt/workarea/VGMFileListView.cpp, src/ui/qt/workarea/VGMFileListView.h
This updates the RawFileListView class to use MenuManager. To enable this, I made some small changes to various MenuManager-related classes.
It may look like a lot of changes to the MenuManager, but rest assured, it's mostly moving stuff around. The only logical changes there are to make MenuManager a singleton, make SaveAsOriginalFormatCommand a generic class, and update the RawFile menu registration.
- generalize SaveAsOriginalFormatCommand so that it will support any class that implements a SaveAsOriginal() method
- reorder the Close command in VGMFile menus
- flesh out the RawFile MenuManager menu and use it in RawFileListView
- make MenuManager a singleton()
- move Command base class and types into its own header file to resolve circular dependency
It would be good to unify context …
=> Use MenuManager with RawFileListView. Minor reorganization of MenuManager classes

src/main/Root.cpp, src/main/components/Matcher.cpp, src/main/components/Matcher.h, src/main/components/VGMColl.cpp, src/main/components/VGMColl.h, src/main/conversion/VGMExport.cpp, src/main/conversion/VGMExport.h, src/main/formats/Akao/AkaoFormat.cpp, src/main/formats/Akao/AkaoFormat.h, src/main/formats/CPS/CPS1Scanner.cpp, src/main/formats/CPS/CPS2Scanner.cpp, src/main/formats/HOSA/HOSAScanner.cpp, src/main/formats/MP2k/MP2kScanner.cpp, src/main/formats/NDS/NDSScanner.cpp, src/main/formats/TriAcePS1/TriAcePS1Scanner.cpp, src/ui/cli/CLIVGMRoot.cpp, src/ui/qt/ManualCollectionDialog.cpp, src/ui/qt/SequencePlayer.cpp, src/ui/qt/workarea/VGMCollListView.cpp, src/ui/qt/workarea/VGMCollView.cpp
This makes every VGMColl member private, adds getters for the vector collections (instrSets(), sampColls(), miscFiles()), and renames all methods and fields to comport with our new style.
Like RawFile, it's necessary to rename GetName() -> name() to for VGMColl to work with the MenuManager SaveCommand class.
As before, I will add this commit to the .git-blame-ignore-revs file in the next PR.
=> VGMColl field and method name cleanup

src/main/components/seq/VGMSeqNoTrks.h
Apparently #495 broke the VGMSeqNoTrks class.
Verified it's no longer causing an infinite loop.
=> Fix rawFile() call causing infinite recursion

src/main/formats/CPS/CPS2Format.h, src/main/formats/CPS/CPS2Instr.cpp, src/main/formats/CPS/CPS2Instr.h, src/main/formats/CPS/CPSTrackV1.cpp, src/main/formats/CPS/CPSTrackV2.cpp
There's no perfect way to convert % amplitude curves to the decibel (logarithmic) curves of SF2 and DLS, but this shortens the timing and sounds more accurate. I also rewrote non-BPM tempo event logic to employ the IRQ rate constants instead of relying on magic numbers.
Tested affected formats.
=> CPS3 improve ADSR timing, clean up tempo logic

src/main/formats/CPS/CPSTrackV1.cpp, src/main/formats/CPS/CPSTrackV2.cpp, src/main/formats/MP2k/MP2kInstrSet.cpp, src/main/formats/SquarePS2/SquarePS2Seq.h
- Fix MP2k not loading sample collections. `LoadInstrs()` had included the odd instruction `sampColl == nullptr;` which I unthinkingly assumed should be corrected to `sampColl = nullptr;` in one of my cleanup PRs. Nope.
- Fix SquarePS2 matching not working due to the declaration of GetID() having changed to const (`uint32_t GetID() const`) and SquarePS2Seq not updating its method signature (and not using the override keyword, which would have caught this). I've verified this is the only format with the issue.
- Small cleanup of checking for and adding EndTrack events when they occur after forever loops in CPSSeq.
=> Fix MP2k And SquarePS2 issues

.git-blame-ignore-revs, bin/mame_roms.xml
Also, add missing sound roms for sfiii2 in mame_roms.xml.
Looks like rebase and merge changes the commit hashes even if no rebase is necessary.
=> Fix .git-blame-ignore-revs commit hash

.git-blame-ignore-revs
Updating the last commit hash after a rebase and merge.
=> Update .git-blame-ignore-revs for Qt implementation method renaming

src/ui/qt/workarea/HexView.cpp, src/ui/qt/workarea/HexView.h, src/ui/qt/workarea/MdiArea.cpp, src/ui/qt/workarea/VGMFileView.cpp, src/ui/qt/workarea/VGMFileView.h
A lot of little performance optimizations for HexView:
- hack fix for paintEvents being called for all open subwindows of the MDI, not just the active one
- draw the selected item pixmap by copying segments of cached line pixmaps when possible (virtually, always) instead of calling the various print() methods to draw from scratch
- optimize paintEvent for happy path - construct a QPixmap and QPainter only when a line isn't in cache.
- memoize getVirtualWidth() methods calculated values. They are invalidated on font change
- memoize a new charHalfWidth() value, also invalidated on font change
- only redraw the overlay when window height expands beyond its current height (don't redraw when window height shrinks)
- skip drawing lines that are totally eclipsed by the selected item
- MacOS: …
=> HexView optimizations

src/ui/qt/util/UIHelpers.cpp, src/ui/qt/util/UIHelpers.h, src/ui/qt/workarea/HexView.cpp, src/ui/qt/workarea/HexView.h
This is a follow up to the previous PR #514. I will merge them together, because...
#514 added a regression. One thing I tacked on was brightening the selection overlay by reducing the final opacity of the animated QGraphicsOpacityEffect.  It turns out that an overlaid widget using a QGraphicsOpacityEffect with an opacity value between 0 and 1 (exclusive) hurts draw performance. The solution is to animate to a full 1.0 opacity (as before), and instead reduce the alpha of the fill color that we use to paint the overlay. This is the cleaner solution anyway.
Other changes:
- Solved a bug that was causing the full QScrollArea viewport to be invalidated on a scroll - ie. HexView was redrawing every visible line (albeit with pixmap caches) on each draw pass. The bug is that we're setting the …
=> HexView optimizations part 2

src/ui/qt/main_ui.cpp, src/ui/qt/workarea/HexView.cpp, src/ui/qt/workarea/HexView.h
On the animation side:
- Animate the `blurRadius` and `offset` properties of the selectionView's QGraphicsDropShadowEffect, which is now applied to the widget instead of exclusively used at draw time
- On deselection, instead of immediately hiding the selected item view (which can cause a sort of flash effect), keep it visible and reverse animate its shadow effect alongside the overlay fade in, then hide it afterward.
- I also deepened the shadow by increasing the offset.
On the performance side:
- I refactored the animation code. It's much simpler now. Instead of deleting and recreating animations, it now uses pause() and setDirection() for animation interruption and reversal. The three QPropertyAnimations are bucketed into a QParallelAnimationGroup.
-  Both the `overlay` and …
=> Hexview: improve animation and performance

src/main/components/seq/VGMSeq.h, src/main/formats/Akao/AkaoSeq.cpp, src/main/formats/FFT/FFTSeq.cpp, src/main/formats/HOSA/HOSASeq.cpp, src/main/formats/SonyPS2/SonyPS2Seq.cpp, src/main/formats/SquarePS2/SquarePS2Seq.cpp, src/main/formats/TriAcePS1/TriAcePS1Seq.cpp
In #510, I made a mistake and replaced a few calls to UseLinearAmplitudeScale() with the new getter method `usesLinearAmplitudeScale()` rather than new setter method `setUseLinearAmplitudeScale()`. This screwed up volume on these formats.
I have corrected the mistake, and added [[nodiscard]] to the various VGMSeq methods that get such conversion properties to help prevent any future screwups.
=> Fix usesLinearAmplitudeScale() regression

src/main/components/Matcher.h, src/main/components/seq/VGMSeqNoTrks.h, src/main/formats/SonyPS2/SonyPS2Scanner.cpp, src/main/formats/SonyPS2/SonyPS2Seq.cpp, src/main/formats/SonyPS2/SonyPS2Seq.h, src/main/io/RawFile.h
A couple issues addressed here:
- FileNameMatcher never sets the id for any of its file types, and is therefore totally broken. 
- VirtFile::extension() returns the extension of its parent raw file by default. This is undesirable, as we would usually prefer to get the extension of the filename of the VirtFile. For example, when extracting a psf2, the SonyPS2 scanner needs to know the extension of the sample collection file.
I've fixed FileNameMatcher and reversed the VirtFile::extension() logic so that it returns the VirtFile name extension first, and if none exists, the parent RawFile's extension.
This fixes detection of SonyPS2 collections.
I tested that every format is still detected correctly.
=> Fix FileNameMatcher and VirtFile::extension()

src/main/formats/Akao/AkaoFormat.cpp, src/main/formats/Akao/AkaoFormat.h, src/main/formats/Akao/AkaoInstr.cpp, src/main/formats/Akao/AkaoInstr.h, src/main/formats/Akao/AkaoMatcher.cpp, src/main/formats/Akao/AkaoMatcher.h, src/main/formats/Akao/AkaoScanner.cpp, src/main/formats/Akao/AkaoSeq.cpp, src/main/formats/Akao/AkaoSeq.h, src/main/formats/CPS/CPSSeq.cpp
This provides three improvements to the Akao format:
1. Adds support for creating collections that use more than one sample collection (Vagrant Story, FF8, others?)
2. Adds a new AkaoMatcher class that better handles the complicated task of determining what files belong in an Akao collection
3. Combines instrument region ADSR with articulation data ADSR, as opposed to only utilizing the articulation data ADSR. This fixes a lot of tracks with broken-sounding instruments.
Heads up that the Akao format itself is a complete mess. For the sake of matching, the relevant facts are:
1. Sequences and instrument sets are bundled together effectively as one file in their original format, so they are given the same id when we create them in the scanner.
2. Sequences may contain a byte that indicates …
=> Akao Format improvements

src/main/formats/Akao/AkaoFormat.cpp, src/main/formats/Akao/AkaoMatcher.cpp, src/main/formats/Akao/AkaoMatcher.h, src/main/formats/Akao/AkaoScanner.cpp
This PR is branched off of `akao-matcher` and rebased on top of `scanner-format`. It's probably best to ignore it until those PRs are addressed.
This follows up on #527 and the discussion in #526 to add an onFinishedScan() callback to AkaoMatcher. This vastly improves the efficacy of AkaoMatcher.
This is working with every PSF set I have tested, and is able to match files within ISO images for games that use a single sample collection per song with ID associations.
=> AkaoMatcher onFinishedScan()

src/main/components/PSFFile.cpp, src/main/components/PSFFile.h, src/main/components/SPCFile.cpp, src/main/components/SPCFile.h, src/main/components/VGMTag.cpp, src/main/components/VGMTag.h, src/main/formats/Akao/AkaoSeq.cpp, src/main/io/RawFile.cpp, src/main/io/RawFile.h, src/main/loaders/PSFLoader.cpp, src/main/loaders/SPCLoader.cpp
In light of feedback on #530, I decided to refactor SPCLoader so that it's more consistent with PSFLoader. SPC files are now loaded into an SPCFile class. Thereafter, we generate the VGMTag via tagFromSPCFile(). Likewise, I've added a tagFromPSFFile() function, and per my changes in #530, I've fixed the VirtFile constructor to actually set the RawFile::tag field.
I've also added a RawFile::readNullTerminatedString() method, as this logic was needed for reading the id666 tags, and I figure it might be generally useful.
I still wonder if it would be cleaner to make tagFromXFile() static methods of the PSF/SPCFile classes.
Unrelated: I've updated the Akao note velocity from 100 to 127. 
Verified the PSF tags are being set. Tested on SPC files with regular id666 tags and SPC files with …
=> Add SPCFile, fix tags for PSFFile

README.md, src/main/components/instr/VGMInstrSet.cpp, src/main/formats/Akao/AkaoScanner.cpp
Some Akao sets have no instruments defined, but instead only use "articulation" based program changes. Those instruments are generated on the fly via AkaoColl::preSynthFileCreation and deleted afterward via AkaoColl::postSynthFileCreation.
VGMInstrSet was deleting all instruments sets that have no instruments defined post-load. Prior to the major refactor, we got around this with a flag. I have instead just removed the condition altogether.
I've also updated the hack that loads FF7 psfs, though I'm not sure how to properly integrate the second sample collection for the final boss music. Its inclusion was causing problems, so I commented it out.
Finally, I updated the README to reflect changes  in supported formats.
Fix the rest of the Akao games.
Aside from relevant Akao games, I ran …
=> Allow instrument sets with no defined instruments

src/main/formats/Akao/AkaoMatcher.cpp
A couple small changes:
- prioritize most-recently scanned files when searching for associated sample collection
- ignore associated sample collection id of 0, as this is most likely an invalid, optimized-out value
This fixes some issues when loading multiple psf sets at a time
=> minor AkaoMatcher improvements

src/main/components/SPCFile.cpp, src/main/formats/SegSat/SegSatScanner.cpp
- change a SegSatScanner error log to debug, also break at that point instead of continuing to scan the potential sequence list
- report unhandled id6 tag type as an info log instead of warning
Reduce user confusion - we had issues reported due to these two log messages.
=> Change the category of log messages causing confusion

src/ui/qt/workarea/MdiArea.cpp, src/ui/qt/workarea/VGMCollView.cpp, src/ui/qt/workarea/VGMCollView.h, src/ui/qt/workarea/VGMFileListView.cpp
- VGMCollView: support context menus for files
- VGMCollView: allow multiple file selection
- Update MDIArea to return focus to the caller of a VGM file selection notification if a descendant of the caller has focus
- VGMFileListView: prevent a recursive call to Notification::selectVGMFile() within onVGMFileSelected()
This enables context menus for files in the "Selected Collection" view, and makes its selection behavior consistent with VGMFileListView.
Since all conversion must happen via right-click context menus at the moment, it's best we eliminate any barriers to discoverability or potential sources of confusion.
This is the last UI feature I want to get in before a release.
General attempts to break it.
=> Add context menus to VGMCollView

src/main/components/seq/SeqTrack.cpp, src/main/components/seq/SeqTrack.h, src/main/formats/Akao/AkaoInstr.cpp, src/main/formats/Akao/AkaoSeq.cpp, src/main/formats/Akao/AkaoSeq.h
- AkaoPS1: add proper portamento support
- AkaoPS1: reinterpret the absolute fine tuning event as pitch bend, as multiple games use it this way (Racing Lagoon, Saga Frontier 2, for ex)
- AkaoPS1: add a fix for malformed key low / high regions in split-key instruments (affects Saga Frontier 2, Racing Lagoon, maybe others)
- AkaoPS1: use drumkit instrument ADSR overrides like we added for melodic instruments
- SeqTrack:: add SeqTrack::addPitchBendAsPercent() method 
MIDI Fine Tune events don't change the pitch of active notes, but a lot of tracks use the events we've named "EVENT_TUNING_ABS" as a pitch bend affecting active notes.
We should probably also change the relative fine tuning event to be pitch bend, but I didn't find any games that use this event so I couldn't test a change. I …
=> AkaoPS1 pitch events

src/main/Root.cpp, src/main/Root.h, src/main/components/Matcher.cpp, src/main/components/Matcher.h, src/main/components/Scanner.cpp, src/main/components/Scanner.h, src/main/formats/Akao/AkaoMatcher.h, src/main/formats/Akao/AkaoScanner.cpp, src/ui/cli/CLIVGMRoot.cpp, src/ui/cli/CLIVGMRoot.h, src/ui/cli/main_cli.cpp
This should vastly improve the reliability of FileGroupMatcher.
- add Matcher::onFinishedScan as virtual method
- Root now calls onFinishedScan after each scan()
- refactor FileGroupMatcher - it now utilizes onFinishedScan() and does not retain state between RawFile loads
- remove obviated code in CLIVGMRoot
This is an extension of the work I did on AkaoMatcher (#527 and #528), specifically around adding a Format to the Scanner class so it can invoke an `onFinishedScan()` callback on Matcher when a RawFile has finished loading. `onFinishedScan()` is now a virtual method of Matcher, and it is invoked in VGMRoot::setupNewRawFile() after scanning a file.
I've updated the logic of FileGroupMatcher so that it works in the simple way I had originally envisioned - it assumes an association …
=> Refactor FileGroupMatcher

src/main/Root.h, src/main/components/VGMColl.cpp, src/main/conversion/SF2File.cpp, src/main/formats/HOSA/HOSAScanner.cpp, src/main/formats/PS1/Vab.cpp, src/main/formats/common/PSXSPU.cpp, src/main/io/RawFile.h, src/main/loaders/PSFLoader.cpp, src/main/loaders/RSNLoader.cpp, src/main/loaders/SPC2Loader.cpp
This is a collection of fixes for improving detection of PS1 / PSF formats:
- additional psflib file tags start at _lib2 per the spec. we were search for _lib1 and stopping when we couldn't find it
- add file size checks to various Loader classes. Was throwing errors for some PSF collections where the psf files themselves contains no content, but loads multiple psflib files.
- loosened a PSXSampColl detection heuristic that was causing a false negative on Philosoma
- clamp the VAB region pitch tune value to 127. This fixes MegaMan 8, which uses values > 0x7F but apparently expects them to be clamped. Also consistent with gocha's comment.
- reject PSXSampColls size 32 bytes or less. This was allowing more false positives through.
- add Root::variantToType<>() and …
=> PS1 / PSF fixes

src/main/components/Matcher.cpp, src/main/formats/Akao/AkaoMatcher.cpp, src/main/formats/Akao/AkaoSeq.cpp, src/main/formats/CPS/CPSTrackV1.cpp, src/main/formats/SquarePS2/WD.cpp, src/main/formats/common/PSXSPU.cpp
- Rewrite PSX (and PS2) ADPCM sample collection detection
- CPS1: remove debug line that set FM track volumes to 0
- AkaoPS1: add a default volume, set it to max
- SquarePS2: remove totally wrong velocity region stuff
- AkaoMatcher: no longer require that every articulation id be accounted for to create a collection
- FilegroupMatcher: prioritize for size when matching the last of any collection type. Helps match PSFs that contain dummy files.
PSX ADPCM detection: tested extensively against PSF sets and CD images.
AkaoMatcher: tested against most AKAO sets.
=> Format fixes / PSX ADPCM detection rewrite

src/main/components/VGMItem.cpp, src/main/components/VGMItem.h, src/main/components/instr/VGMInstrSet.cpp, src/main/components/seq/VGMSeqNoTrks.cpp, src/main/formats/TamSoftPS1/TamSoftPS1Instr.cpp
* add VGMItem::transferChildren()
* VGMInstrSet: transfer child items of internal sample collections to the instrument set so they appear in the file structure view
* TamSoftPS1: fix the instrument set prematurely loading the internal sample collection and not assigning it to the sampColl property instead.
In conjunction with PR #548, this will fix #547 .
=> Add samples to instrument sets with internal sample collection, fix TamSoftPS1 issue #547

src/main/formats/FFT/FFTSeq.cpp, src/ui/qt/ManualCollectionDialog.cpp
* ManualCollectionDialog now uses the newCollection() factory method of the selected sequence's format to construct its collection
* ManualCollectionDialog now calls VGMColl:load() instead of just Root::addVGMColl()
* Fix reading of null byte in FFT sequence filename strings
This allows the ManualCollectionDialog to work with formats that use custom VGMColl classes to load their collections. For now, this is only applicable to AkaoPS1.
Tested manual collection loading on a few different formats. One interesting complication is that multi sample collection Akao collections are sensitive to the order of the sample collections in the sampColls vector. It would be ideal for the UI to allow reordering of VGMFiles within the collection file vectors.
=> Update ManualCollectionDialog to use Format::newCollection() and VGMColl::load()

bin/mame_roms.xml, src/main/formats/CPS/CPS1Instr.cpp, src/main/formats/CPS/CPS1Instr.h, src/main/formats/CPS/CPS1Scanner.cpp, src/main/formats/CPS/CPS2Instr.h, src/main/formats/CPS/CPSTrackV1.cpp, src/ui/qt/services/MenuManager.cpp, src/ui/qt/services/commands/SaveCommands.h
This pulls in some work done on the juce3 branch which converts CPS1 instrument set data for the YM2151 chip into the [OPM file format](https://vgmrips.net/wiki/OPM_File_Format).
I am working on implementing actual YM2151 playback within the juce3 branch, but some necessary work can be done on the master branch. For example, as we support formats beyond sampled instrument sets like SoundFont 2, it seems necessary to refactor our conversion code a little bit. We'll need a way for collections and instrument sets to indicate the formats they can be converted to, and we'll want some abstraction around the the conversion process so that the base classes don't require any specific format knowledge.
I'm planning to work on this refactor next.
Exporting has worked with every CPS1 set I've tried. …
=> add CPS1OPMInstrSet and OPM file export

CMakeLists.txt
Replace fallback version string `v$(CMAKE_PROJECT_VERSION)` with `v${CMAKE_PROJECT_VERSION}`.
If Git is not available, the application version would be set to `v$(CMAKE_PROJECT_VERSION)`. This is a literal string and the version does not get substituted by CMake. It should be `v${CMAKE_PROJECT_VERSION}` instead.
The version displayed in the Help page is incorrect.
Noticed during packaging in Nixpkgs: https://github.com/NixOS/nixpkgs/pull/321129#issuecomment-2466679937
Rebuilt the application in Nixpkgs with this patch applied
Before:
=> Fix fallback version string in build script

src/main/formats/PS1/Vab.cpp
This fixes parsing of the sample data in PS1 VAB files (i.e. VH and VB combined into one file).
When the `Vab` class reads the VAB header, it creates a vector `vagLocations` with the offset and size of each VAG audio sample. It then creates a `PSXSampColl` and passes it the `vagLocations` so that it can read the samples. The base (`dwOffset`) of the `PSXSampColl` is the start of the sample data (the VB portion of the VAB file), but the offsets in `vagLocations` are relative to the beginning of the file (the VH portion of the VAB file), so all the reads of the sample data are offset by one header length and the samples are cut off at the beginning. This PR changes `vagLocations` to be relative to the start of the VB data.
I tested this with VAB files from two different games and verified …
=> Vab: VAG locations should be relative to the start of the sample data

src/main/components/seq/SeqTrack.cpp, src/main/components/seq/SeqTrack.h, src/main/formats/AsciiShuichiSnes/AsciiShuichiSnesFormat.h, src/main/formats/AsciiShuichiSnes/AsciiShuichiSnesInstr.cpp, src/main/formats/AsciiShuichiSnes/AsciiShuichiSnesInstr.h, src/main/formats/AsciiShuichiSnes/AsciiShuichiSnesScanner.cpp, src/main/formats/AsciiShuichiSnes/AsciiShuichiSnesScanner.h, src/main/formats/AsciiShuichiSnes/AsciiShuichiSnesSeq.cpp, src/main/formats/AsciiShuichiSnes/AsciiShuichiSnesSeq.h, src/main/formats/CPS/CPS1Instr.cpp
This adds support for SNES music drivers by ASCII corporation, designed by Shuichi Ukai.
Specifically, music from Wizardry VI and Down the World (#365) will now be supported.
There should be other game titles that use the same drivers, but I have not tested those so far.
In the process, I have fixed a very small problems with vgmtrans core. (see commit log).
Confirmed that Wizardry VI and Down the World music can be played.
Not tested on anything other than Windows 11, Visual Studio 2022.
I haven't done much regression testing because I haven't made aggressive changes other than adding code.
**Supported**:
* Wizardry VI: Bane of the Cosmic Forge
* Down the World: Mervil's Ambition
**No Support Guaranteed (it may or may not work)**:
* Ardy Lightfoot
* Derby Stallion II
* Sanrio Shanghai
* …
=> AsciiShuichiSnesFormat: New SNES format supporting Wizardry VI and Down the World

src/main/formats/NDS/NDSSeq.cpp
This change adjusts the size read for the actual file interactions to equal the size in the header. Previously this size was read as a short even though the header contains a word field for size.
Dragon Quest VI - Realms of Reverie contains SND_BGM_M30_LULLABY which has a size of 0x1a228 and was previously not parsable.
=> Fix SSEQ file size read

src/ui/qt/workarea/MdiArea.cpp, src/ui/qt/workarea/MdiArea.h
This adds conventional keyboard shortcuts to switch between VGMFileView tabs.
On MacOS, I've added Cmd-Shift-BracketLeft/Right, Cmd-Opt-ArrowLeft/Right, and Ctrl+PageUp/Down.
Windows and Linux get Ctrl-Tab/Ctrl-Shift-Tab and Ctrl-PageUp/Down.
Tested on MacOS and Windows.
=> Switch tab keyboard shortcuts

src/main/formats/PS1/PS1Seq.cpp, src/main/formats/PS1/PS1Seq.h, src/main/formats/PS1/PS1SeqScanner.cpp, src/main/formats/PS1/Vab.cpp, src/main/formats/common/PSXSPU.cpp
Improvements to PSX ADPCM scanning:
- handle case where frame data for a given sample extends beyond the first frame with end flag set
- do frame header byte validation at every iteration of back scan
- add check to ensure loaded sample collections are greater than the number of bytes back-scanned
PS1Seq:
- default program assignment to channel number
VAB:
- remove loading of bundled VAGS. Was proving unreliable
Ran it against a large swath of games, mostly PSF
=> More PS1 scanning improvements

src/main/formats/common/PSXSPU.cpp, src/main/formats/common/PSXSPU.h
This rewrites the PSX ADPCM sample decompression algorithm with a lot of help from ChatGPT o3. I found that the previous version was potentially clipping samples (ex: FFIX - Crossing Those Hills sample 18, heard obviously in sample and faintly at end of song). This clipping is inconsistent and depends on the compiler used. 
It looks like the `decompVAGBlk()` function was doing some bit manipulation / casting that caused implementation-defined behavior. Also, probably most critically, it wasn't clamping the value to the signed 16 bit range.
This new implementation is int instead of float based and should be more reliable and faster. I dug into the logic and compared against another [int based implementation](https://github.com/vgmstream/vgmstream/blob/1ef807b594be26c57c4d004bec23f5b296d4999 …
=> rewrite of PSXSPU::decompVAGBlk(). fixes potential clipping

src/main/formats/Akao/AkaoSeq.cpp, src/main/formats/Akao/AkaoSeq.h, src/ui/qt/util/Helpers.cpp
- AkaoSeq: use fmt::format in place of stringstream
- AkaoSeq: simplify logUnknownEvent()
- fix VGMItem::Type::Unknown event color
Tested that event strings are working as expected. Also verified logUnknownEvent output.
=> AkaoSeq: use fmt::format in place of stringstream

src/main/components/seq/SeqTrack.h, src/main/formats/AkaoSnes/AkaoSnesSeq.cpp, src/main/formats/ChunSnes/ChunSnesSeq.cpp, src/main/formats/CompileSnes/CompileSnesSeq.cpp, src/main/formats/FalcomSnes/FalcomSnesSeq.cpp, src/main/formats/GraphResSnes/GraphResSnesSeq.cpp, src/main/formats/HeartBeatSnes/HeartBeatSnesSeq.cpp, src/main/formats/HudsonSnes/HudsonSnesSeq.cpp, src/main/formats/ItikitiSnes/ItikitiSnesSeq.cpp, src/main/formats/KonamiPS1/KonamiPS1Seq.cpp, src/main/formats/KonamiSnes/KonamiSnesSeq.cpp, src/main/formats/MoriSnes/MoriSnesSeq.cpp, src/main/formats/NamcoSnes/NamcoSnesSeq.cpp, src/main/formats/NeverlandSnes/NeverlandSnesSeq.cpp, src/main/formats/NinSnes/NinSnesSeq.cpp, src/main/formats/PandoraBoxSnes/PandoraBoxSnesSeq.cpp, src/main/formats/PrismSnes/PrismSnesSeq.cpp, src/main/formats/RareSnes/RareSnesSeq.cpp, src/main/formats/SoftCreatSnes/SoftCreatSnesSeq.cpp, src/main/formats/SuzukiSnes/SuzukiSnesSeq.cpp, src/main/formats/TamSoftPS1/TamSoftPS1Seq.cpp
Replace stringstream usages in format files with std::string and fmt::format().
This PR was initially created as a test of OpenAI's new Codex service. After many prompts, I have coaxed Codex into performing an extensive refactor. I have now reviewed the changes and made additional commits to improve some of the interpolation (forcing unsigned chars to int format) and code formatting. I expect this PR fixes many instances of event descriptions which print parameters as ASCII characters instead of integers.
I have done basic testing, but nothing extensive given the scope of the refactor.
=> Remove stringstream usage from formats

src/main/components/seq/SeqEvent.cpp, src/main/components/seq/SeqEvent.h, src/main/components/seq/SeqTrack.cpp, src/main/components/seq/SeqTrack.h, src/main/conversion/SF2Conversion.cpp, src/main/formats/KonamiArcade/KonamiArcadeInstr.cpp, src/main/formats/KonamiArcade/KonamiArcadeSeq.cpp, src/main/formats/KonamiArcade/KonamiArcadeSeq.h
This improves conversion of the Mystic Warrior driver (KonamiArcade) and adds the CoarseTuningSeqEvent and related SeqTrack methods. Additionally, this adds state member variables to SeqTrack to track fine tuning (`fineTuningCents`) and coarse tuning (`coarseTuningSemitones`) values.
For the KonamiArcade driver, this specifically:
* adds events F6 and F7 which affect control flow. F6 sets a start marker, the next call to F7 sets an end marker, subsequent calls to F7 are like subroutine calls, jumping to the start marker and returning at the end marker
* adds event EB, which is an alternative means of setting percussion mode (don't know how it's unique from event 60)
* adds event EC - transpose. Because percussion mode uses a drum kit style instrument, I use coarse fine tuning instead of …
=> KonamiArcade update and CoarseTuningSeqEvent

src/main/formats/KonamiArcade/KonamiArcadeInstr.cpp, src/main/formats/KonamiArcade/KonamiArcadeSeq.cpp, src/main/formats/KonamiArcade/KonamiArcadeSeq.h
KonamiArcade:
* add Portamento event
* add Pitch Slide Mode event
* handle loop transpose param (used for glissandos)
KonamiArcadeInstr:
* add an artificial release time value for instruments and drumkits
Also I've added the method `KonamiArcadeTrack::makeTrulyPrevDurNoteEnd()`. I may add a separate PR adding a better named function in SeqTrack (and likely renaming `SeqTrack::makePrevDurNoteEnd()`) Unlike `SeqTrack::makePrevDurNoteEnd()`, which can modify multiple duration note events, `makeTrulyPrevDurNoteEnd()` will only affect the last duration note added.  The former was inadvertently modifying multiple note events in the portamento logic.
This sounds worlds better on the juce3 branch. BASS doesn't support 14 bit portamento time, and its portamento handling seems off in general.
=> KonamiArcade: add Portamento and Pitch Slide Mode

src/main/components/instr/VGMSamp.cpp, src/main/components/instr/VGMSamp.h, src/main/formats/KonamiArcade/KonamiArcadeInstr.cpp, src/main/formats/KonamiArcade/KonamiArcadeInstr.h, src/main/formats/KonamiArcade/KonamiArcadeSeq.cpp, src/main/formats/common/KonamiAdpcm.cpp
Though it's sparsely used, Konami's K054539 sound chip supports a playback mode that reads samples in reverse. In both the hardware register and the sample info data, this mode is indicated by bit 5 of the byte that also determines sample type (8 bit PCM, 16 bit PCM, or ADPCM). So 0x20, 0x24, and 0x28 indicate reverse samples of those respective types.
An example of actual usage would be the Speak & Spell-esque synthesized voice 10 seconds into Mystic Warriors song 0.
In addition to updating the KonamiArcade sample info struct to provide this flag (via a reverse() method), I updated VGMSamp to support reverse samples. I also added reverse support for K054539AdpcmSamp, though I've yet to find an instance where it's used.
The second change I've made is supporting instrument sets with > 127 …
=> KonamiArcade: support reverse samples and program changes > 127

src/main/components/seq/SeqEvent.cpp, src/main/components/seq/SeqEvent.h, src/main/components/seq/SeqTrack.cpp, src/main/components/seq/SeqTrack.h, src/main/conversion/MidiFile.cpp, src/main/conversion/MidiFile.h, src/main/formats/CPS/CPS2Seq.cpp, src/main/formats/CPS/CPS2TrackV1.cpp, src/main/formats/CPS/CPS2TrackV2.cpp, src/main/util/ScaleConversion.cpp
I noticed that my last PR broke volume in CPS2TrackV2 due to the amplitude scale conversion being applied twice. In the course of fixing this, I've tried to remove repetitive code in SeqTrack which handles volume conversion (for Volume, Expression, and Master Volume events).
I also realized that it's silly that we have no methods for adding volume events that take percent values. Right now, we receive a 7-bit integer value which we then convert to a percent, then (usually) convert the scale, then convert back to 7-bit MIDI values. We should have the option to pass volume as a percent in the first step, so I've added overloaded `addVol()` and `addExpression()`. In time, I'd like to do the same for the `insert` and `NoItem` variant methods, and also note velocity. It's more intuitive except …
=> Volume logic refactoring

.gitmodules, src/main/CMakeLists.txt, src/main/components/PSFFile.cpp, src/main/loaders/CHDLoader.cpp, src/main/loaders/CHDLoader.h, src/main/loaders/PSF2Loader.cpp, src/main/util/decompression.h
This adds support for loading chd files, a compression format for cd-rom and hard drive images. It adds [libchdr](https://github.com/rtissera/libchdr) as a git submodule and dependency.
Note that I ran into some difficulties with libchdr's zlib dependency. Specifically, libchdr's CMake files were detecting our `zlibstatic` target and trying to use it, even though it was the non-zlib API compatible version of zlib-ng (and libchdr uses original zlib). To solve the error, I enabled the `ZLIB_COMPAT` option on zlib-ng and updated our usage of the API to the old zlib function names. The change was trivial and mainly involved removing prefixes from function and type names. Now libchdr can utilize our existing zlib-ng dependency.
CHD is an increasingly popular cd-rom image format and also …
=> add CHDLoader and libchdr dependency as git submodule

src/main/components/instr/VGMRgn.cpp, src/main/components/instr/VGMRgn.h, src/main/components/instr/VGMSamp.cpp, src/main/components/instr/VGMSamp.h, src/main/components/seq/SeqTrack.cpp, src/main/conversion/DLSConversion.cpp, src/main/conversion/SF2Conversion.cpp, src/main/conversion/SF2File.cpp, src/main/conversion/SynthFile.cpp, src/main/conversion/SynthFile.h, src/main/formats/Akao/AkaoInstr.cpp, src/main/formats/CPS/CPS2Instr.cpp, src/main/formats/CompileSnes/CompileSnesSeq.cpp, src/main/formats/KonamiArcade/KonamiArcadeInstr.cpp, src/main/formats/MP2k/MP2kInstrSet.cpp, src/main/formats/PrismSnes/PrismSnesInstr.cpp, src/main/formats/SonyPS2/SonyPS2InstrSet.cpp, src/main/formats/common/PSXSPU.h, src/main/formats/common/SNESDSP.cpp, src/main/formats/common/SNESDSP.h, src/main/util/ScaleConversion.cpp, src/main/util/ScaleConversion.h
This is a collection of changes primarily to fix or improve volume calculation and ADSR decay/release timing.
The two most impactful changes:
1) I've removed `convertLogScaleValToAtten()`, which was used for converting instrument/sample attenuation and sustain level values in instrument sets. It assumed the given percent value was using a logarithmic scale of amplitude. I suspect that no format is expressing volume this way. Far more likely is that values represent a percent of amplitude. I've replaced all instances of usage with `convertPercentAmplitudeToAttenDB()`. I think things sound better, and I've spotted no problems. To be clear, I suspect I am the original creator of this function, and made this mistake very early in development.
2) Second, I've revamped …
=> Volume fixes, decay rate improvement

src/main/components/instr/VGMRgn.h, src/main/conversion/SF2Conversion.cpp, src/main/conversion/SF2File.cpp, src/main/conversion/SynthFile.cpp, src/main/conversion/SynthFile.h
When a finetune is assigned to a VGMRgn, we've been applying it to its associated sample instead of to the region in generated SF2 files. This fixes that, and also adds coarse tune.
Multiple regions can be associated with the same sample, but use different finetunes. Moreover, a sample and regions using that sample can each have unique finetunes applied. The old logic broke under these scenarios.
Sequences with finetune are sounding correct.
=> Fix region finetune application in SoundFont files

src/main/components/instr/VGMRgn.cpp, src/main/components/instr/VGMSamp.cpp, src/main/components/instr/VGMSamp.h, src/main/conversion/SF2File.cpp, src/main/conversion/SynthFile.cpp, src/main/conversion/SynthFile.h, src/main/util/common.h
- VGMSamp: samples now have endianness and signedness, default to little endian signed.
- VGMSamp: convertToStdWave() now consistently converts big endian samples to little endian and unsigned to signed.
- SF2File: remove redundant initialAttenuation generator
- SF2File: clamp initialAttenuation value to valid range
- SynthFile: rename convertTo16bitSigned() -> convertTo16Bit() and remove signed conversion logic here. Samples come in signed now
- SynthFile: add default values for members
- VGMRgn: add addCoarseTune()
These fixes came up while working on Saturn instrument conversion. The expected format of samples for VGMSamp is confusing. Adding setEndianness() and setSignedness() makes things clearer.
=> Misc fixes for SF2/VGMSamp conversion

src/main/components/seq/SeqTrack.cpp, src/main/components/seq/SeqTrack.h, src/main/components/seq/VGMSeq.h, src/main/components/seq/VGMSeqNoTrks.cpp, src/main/components/seq/VGMSeqNoTrks.h, src/main/formats/common/PSXSPU.cpp, src/main/util/ScaleConversion.h
- SeqTrack: fix call to applyLevelCorrection() so that it passes through the controller type
- SeqTrack: make setTime() and addTime() virtual
- VGMSeqNoTrks: add override implementations of setTime() and addTime()
- VGMSeq: set default value for panVolumeCorrectionMode
- PSXSPU: handle another edge case of weird sample collection layouts
=> More miscellaneous fixes

src/main/Options.h, src/ui/qt/MenuBar.cpp, src/ui/qt/services/Settings.cpp, src/ui/qt/services/Settings.h
We have two classes for storing options:
- the main code has a `ConversionOptions` class
- the qt code has a `Settings` class, which stores UI-specific options
`Settings` uses `QSettings`, which persists to disk. `ConversionOptions` does not persist.
This PR makes `Settings` a superset of the `ConversionOptions` class while preserving the UI-agnosticism of the main codebase. This allows us to centralize all user-configurable options into the `Settings` class and persist `ConversionOptions`.
We achieve this by making a simple key-value interface - `OptionStore` which `ConversionOptions` can load from and save into. On the Qt side, we implement a `QtOptionStore` which wraps a `QSettings` object. We wrap the various ConversionOptions into Settings and save/load the QtOptionStore when they …
=> Interface ConversionOptions with Settings

src/main/Options.h, src/main/components/seq/SeqTrack.cpp, src/main/components/seq/VGMSeqNoTrks.cpp, src/main/components/seq/VGMSeqNoTrks.h, src/main/formats/HeartBeatPS1/HeartBeatPS1Seq.cpp, src/main/formats/NamcoSnes/NamcoSnesSeq.cpp, src/main/formats/PS1/PS1Seq.cpp, src/main/formats/SegSat/SegSatSeq.cpp, src/main/formats/SonyPS2/SonyPS2Seq.cpp, src/ui/qt/MenuBar.cpp, src/ui/qt/services/Settings.cpp, src/ui/qt/services/Settings.h
This adds an option to for skipping MIDI channel 9 (10 in base 1) during conversion. Our code is inconsistent about skipping channel 9, with trackless formats (VGMSeqNoTrks) using channel 9, and regular VGMSeq skipping it. This PR gives more control to the user and clarifies behavior.
_(Side note: VGMMultiSectionSeq also uses channel 9, but that subclass is only utilized by NinSnesSeq, which uses only 8 tracks. NinSnesSeq uses channel 9 for percussion note events, which are seemingly broken independent of this change. I will look into fixing that soon)._
Skipping channel 9 is potentially useful because the channel is reserved by MIDI, SoundFont and DLS for drumkits, some DAWs (and FluidSynth / libbass) will not allow melodic instrument playback by default on the channel. We currently …
=> Add "Skip MIDI Channel 10" conversion option

src/main/components/seq/VGMSeq.cpp, src/main/components/seq/VGMSeq.h, src/main/components/seq/VGMSeqNoTrks.cpp, src/main/components/seq/VGMSeqNoTrks.h, src/main/conversion/VGMExport.h, src/main/formats/Format.h, src/ui/cli/CLIVGMRoot.cpp, src/ui/qt/SequencePlayer.cpp, src/ui/qt/services/commands/SaveCommands.h
This adds the `VGMSeq::useColl()` method, which is called before conversion and can be overridden to give sequences access to collection data. 
This also adds an effective flag on `Format` to indicate that the format uses collection data for sequence data. This flag is checked to display warning toasts when a user converts a sequence with no collection data, or when it's unclear which collection to use.
Some sequence formats require instrument set data for accurate conversion. For example, the Sega Saturn sequence format uses instrument set data for determining velocity values, pitch bend ranges, and portamento timing. The standard SDK PS1 sequence format also requires instrument data, which we haven't utilized yet.
=> Provide collection context for sequence conversion

src/main/formats/KonamiArcade/KonamiArcadeSeq.cpp
I forgot to reset a couple state variables in KonamiArcadeTrack::resetVars(). Unfortunately, this isn't surfacing as a problem in the macOS build, but it is apparent on Windows.
=> Fix unset default values for KonamiArcadeSeq vars

.github/workflows/build.yml, CMakePresets.json, src/ui/qt/CMakeLists.txt
- Update CMakePresets.json to use the "Ninja Multi-Config" generator on macos and linux.
- Update src/ui/qt/CMakeLists.txt to fix macOS POST_BUILD copy_if_different paths with Ninja.
- Update .github/workflows/build.yml to remove redundant parameters after making ninja the default generator
I would like to know if there are good reasons against making ninja the default for all platforms. The benefit is simplicity and a better building experience in CLion. Make doesn't automatically use all logical cores like ninja, which is a pain in the ass. It's elegant to be able to build quickly across all platforms using the same simple commands, for example:
```
cmake --preset macos-x64-clang
cmake --build --preset macos-x64-clang-release --target vgmtrans
```
Successfully built using the above …
=> Update cmake presets to use ninja on mac and linux

src/main/formats/Akao/AkaoMatcher.cpp
Fixing a mistake that was made when updating AkaoMatcher's logic for the PSF overlay update. The logical error causes some PSF sets to not create collections.
=> Fix logic bug in AkaoMatcher
